// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiX7esFt1iKfmZRJPEG06eiptnD2iQDrY',
    appId: '1:287987514435:web:6ef42bdf762eb82026e8f6',
    messagingSenderId: '287987514435',
    projectId: 'food-for-thought-wsu',
    authDomain: 'food-for-thought-wsu.firebaseapp.com',
    storageBucket: 'food-for-thought-wsu.appspot.com',
    measurementId: 'G-P5R084ZJ2S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5xSt_ja6jXfBR_Av5fXWyqHVDwL43bkk',
    appId: '1:287987514435:android:9dbfbcf8d33d0fbe26e8f6',
    messagingSenderId: '287987514435',
    projectId: 'food-for-thought-wsu',
    storageBucket: 'food-for-thought-wsu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTarP8fIQFXSh5Q6kTBfnNMEXFzKDuEec',
    appId: '1:287987514435:ios:531762b3f7dc452e26e8f6',
    messagingSenderId: '287987514435',
    projectId: 'food-for-thought-wsu',
    storageBucket: 'food-for-thought-wsu.appspot.com',
    iosClientId: '287987514435-5fovqseob0kdcof75499117hv0b5u63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodForThought',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTarP8fIQFXSh5Q6kTBfnNMEXFzKDuEec',
    appId: '1:287987514435:ios:531762b3f7dc452e26e8f6',
    messagingSenderId: '287987514435',
    projectId: 'food-for-thought-wsu',
    storageBucket: 'food-for-thought-wsu.appspot.com',
    iosClientId: '287987514435-5fovqseob0kdcof75499117hv0b5u63j.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodForThought',
  );
}
